# Generated by Django 6.1.2 on 2026-10-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='Edad',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='Edad',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='Estudios',
            new_name='estudios',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='tipocurso',
            old_name='Dias',
            new_name='dias',
        ),
        migrations.RenameField(
            model_name='tipocurso',
            old_name='Horas',
            new_name='horas',
        ),
        migrations.RenameField(
            model_name='tipocurso',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
